build-102/src/api/urls.py
from django.urls import path
from api.views import APIView, APIFileView, APIExchangeView

urlpatterns = [
    path('files/<str:id>/<str:method_name>/', APIFileView.as_view(), name='api-file-action'),
    path('files/<str:method_name>/', APIFileView.as_view(), name='api-root-files'),
    path('ping/', APIView.as_view()),
    path('<str:entity_name>/<str:method_name>/', APIView.as_view()),
    path('<str:entity_name>/<str:method_name>/<str:stage>/', APIExchangeView.as_view()),
]

build-102/src/project/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import patterns, include, url
from admin_honeypot.admin import honeypot_site
from main.views import IndexView
from .sitemaps import site_sitemaps


urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^404/$', 'django.views.defaults.page_not_found'),
    url(r'^500/$', 'django.views.defaults.server_error'),
    url(r'^dealers/', include('dealers.urls', namespace='dealers')),
    url(r'^delivery/', include('delivery.urls', namespace='delivery')),
    url(r'^training/', include('training.urls', namespace='training')),
    url(r'^design/', include('design.urls', namespace='design')),
    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^privacy-policy/', include('policy.urls', namespace='policy')),
    url(r'^agreement/', include('agreement.urls', namespace='agreement')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^robokassa/', include('robokassa.urls', namespace='robokassa')),
    url(r'^sphinx/', include('libs.sphinx.urls', namespace='sphinx')),

    url(r'^admin/', include(honeypot_site.urls)),
    url(r'^dladmin/ckeditor/', include('ckeditor.admin_urls', namespace='admin_ckeditor')),
    url(r'^dladmin/gallery/', include('gallery.admin_urls', namespace='admin_gallery')),
    url(r'^dladmin/users/', include('users.admin_urls', namespace='admin_users')),
    url(r'^dladmin/ctr/', include('admin_ctr.urls', namespace='admin_ctr')),
    url(r'^dladmin/', include(admin.site.urls)),

    url(r'^away/$', 'libs.away.views.away', name='away'),
    url(r'^rating/', include('rating.urls', namespace='rating')),
    url(r'^ckeditor/', include('ckeditor.urls', namespace='ckeditor')),
    url(r'^blocks/', include('attachable_blocks.urls', namespace='blocks')),
    url(r'^ajaxcache/', include('libs.ajaxcache.urls', namespace='ajaxcache')),
    url(r'^social/', include('social_networks.urls', namespace='social_networks')),
    url(r'^autocomplete/', include('libs.autocomplete.urls', namespace='autocomplete')),
    url(r'^jsi18n/$', 'project.views.cached_javascript_catalog', name='jsi18n'),

    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': site_sitemaps}),
    url(r'^api/', include('shop.api_urls')),
    url(r'', include('shop.urls', namespace='shop')),
)

if settings.DEBUG:
    urlpatterns += [
        # Для доступа к MEDIA-файлам при разработке
        url(
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            kwargs={'document_root': settings.MEDIA_ROOT}
        ),
        url(
            r'^static/(?P<path>.*)$',
            'django.views.static.serve',
            kwargs={'document_root': settings.STATIC_ROOT}
        ),
    ]

build-102/src/templates/fields/agreement_field.html
{% load i18n %}

<div class="field {{ field_classes }} {% block add_classes %}{% endblock add_classes %}">
  {% block field %}
    {{ field }}
    <label for="{{ field.id_for_label }}">
      {% url 'policy:index' as policy_url %}
      {% url 'agreement:index' as agreement_url %}
      {% blocktrans %}I agree to the <a href="{{ policy_url }}" target="_blank">regulation</a> and <a href="{{ agreement_url }}" target="_blank">agreement</a> on Private Data Processing{% endblocktrans %}
    </label>
  {% endblock field %}
</div>

build-102/src/templates/fields/field.html
<div class="field {{ field_classes }} {% block add_classes %}{% endblock add_classes %}">
  {% block field %}
    <div class="label-holder">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    </div>

    <div class="control">
      {{ field }}

      {% block errors %}
        {% if form.render_error_message %}
          <div class="error">
            <span>{{ field_errors|first }}</span>
          </div>
        {% endif %}
      {% endblock %}
    </div>
  {% endblock field %}
</div>

build-102/src/templates/fields/search_field.html
<div class="field {{ field_classes }} {% block add_classes %}{% endblock add_classes %}">
  {% block field %}
    <div class="control">
      {{ field }}

      <button type="submit" class="loop"></button>
    </div>
  {% endblock field %}
</div>